# ENTRY POINT
GET http://localhost:3000/

### 

# SIGN UP
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "name":     "Hanzeel",
    "lastName": "Villa",
    "email":    "hvilla0@ucol.mx",
    "username": "Walle",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### 

# LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Walle",
    "password": "12345678"
}

###

# DEVOLVER MASCOTAS DEL USUARIO
GET http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN


###

# DEVOLVER MASCOTA POR ID
GET http://localhost:3000/api/mascotas/ID
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN
###

# CREAR UNA NUEVA MASCOTA
POST http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
    "name": "Viejon",
    "birthDate": "2015-02-27",
    "avatarId": "AVATAR_ID"
}

###

# ACTUALIZAR UNA MASCOTA
PUT http://localhost:3000/api/mascotas/ID
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN
{
    "name": "Diego",
    "birthDate": "2007-05-26",
    "avatarId": "AVATAR_ID" 
}

###

# ELIMINAR UNA MASCOTA
DELETE http://localhost:3000/api/mascotas/ID
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

###

# DEVOLVER AVATARES
GET http://localhost:3000/api/avatares
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

## GET USER REMINDERS
GET http://localhost:3000/api/reminders
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN