# ENTRY POINT
GET http://localhost:3000/

### 

# SIGN UP
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "name":     "Hanzeel",
    "lastName": "Villa",
    "email":    "hvilla0@ucol.mx",
    "username": "Walle",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### 

# LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Walle",
    "password": "12345678"
}

###

# DEVOLVER MASCOTAS DEL USUARIO
GET http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

###

# CREAR UNA NUEVA MASCOTA
POST http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhMjExODg2LWQzZDQtNGQ1Yy04NTkyLWYxYTFkNzgzOTdkMSIsImVtYWlsIjoiaHZpbGxhMEB1Y29sLm14IiwiaWF0IjoxNzQ4MTUzOTE2LCJleHAiOjE3NDg3NTg3MTZ9.u0IHY1p9jcoqXBE8Ca-o9XeTXA7aRPysSZLv-ULGwTM

{
    "name": "Viejon",
    "birthDate": "2015-27-02",
    "avatarId": "YOUR_AVATAR_ID_HERE"
}