# ENTRY POINT
GET http://localhost:3000/

### 

# SIGN UP
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "name":     "Luis",
    "lastName": "Corona",
    "email":    "lcorona11@ucol.mx",
    "username": "Invisible",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### 

# LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "Walle",
    "password": "12345678"
}

###

# DEVOLVER MASCOTAS DEL USUARIO
GET http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

###

# DEVOLVER MASCOTA POR ID
GET http://localhost:3000/api/mascotas/99d3debc-c70e-4461-8a1c-9c204debbcca
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN
###

# CREAR UNA NUEVA MASCOTA
POST http://localhost:3000/api/mascotas
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
    "name": "Ody",
    "birthDate": "2007-05-26",
    "avatarId": "09d245f0-643b-4a40-8f4f-f3ddbb99abc8"
}